### PR TITLE
add API-Doc to doclets.io

### PR DESCRIPTION
**Pull request by lipp**
Adds documentation to [doclets.io](https://doclets.io) service. Future tags and master branch will be published automatically.

[Preview generated with my account](https://doclets.io/lipp/postmark.js/add-to-doclets)

@voodootikigod If you like this, you are very welcomed to login to https://doclets.io with GitHub OAuth. If you don't like it, I'd be happy to hear what you don't like about it :)

Steps required (3min):
1) @voodootikigod  logs in to doclets.io
2) @voodootikigod  adds postmark.js
3) someone merges this PR

### CODE REVIEW

**Comment by lipp** [comment]
@voodootikigod What do you think?

**Comment by lipp** [comment]
@voodootikigod ping :)

**Comment by lipp** [comment]
@voodootikigod @atheken ping :)

**Comment by atheken** [comment]
@lipp This looks pretty cool, we're actually maintaining this module over at https://github.com/wildbit/postmark.js

**Pull request closed without merging**
